// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CardService is the Wails-bound backend for noteit v3 cards. Cards are immutable,
 * append-only journal entries stored as readable Markdown in .noteit/timeline.md.
 * It is a SEPARATE Wails service from NoteService (notes are the secondary, mutable
 * text surface; cards are the primary, immutable surface).
 * 
 * Contract: docs/v3/PLAN.md §1 (entity), §2 (storage) and §2·B (framing/durability).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateCard validates input, resolves tags, assigns a uuid v7 id + timestamp,
 * appends the block durably, and updates the index. Cards are immutable: there is
 * deliberately no UpdateCard/DeleteCard.
 */
export function CreateCard($in: $models.NewCard): $CancellablePromise<$models.Card> {
    return $Call.ByID(1679651441, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCard returns one card by id with derived backlinks (incoming kind=link) and
 * children (incoming kind=parent) computed from the whole store (D.7/D.8).
 */
export function GetCard(id: string): $CancellablePromise<$models.Card> {
    return $Call.ByID(1628100011, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListCards returns cards in creation order (the timeline), optionally filtered.
 * Derived backlinks/children are NOT filled here (cheap list); use GetCard for those.
 */
export function ListCards(filter: $models.CardFilter): $CancellablePromise<$models.Card[]> {
    return $Call.ByID(234843910, filter).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Card.createFrom;
const $$createType1 = $Create.Array($$createType0);
