// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Anchor is a "Level A" code reference: a pin to a file and line range, plus the
 * git commit the project was on when the anchor was made. No content fingerprint
 * yet — if the code moves we can warn (later), but we don't auto-relocate.
 */
export class Anchor {
    "file": string;

    /**
     * "166-195" or a single "42"
     */
    "lines": string;

    /**
     * short git SHA at anchor time
     */
    "commit": string;

    /** Creates a new Anchor instance. */
    constructor($$source: Partial<Anchor> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Anchor instance from a string or object.
     */
    static createFrom($$source: any = {}): Anchor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Anchor($$parsedSource as Partial<Anchor>);
    }
}

/**
 * Card is the in-memory shape of a timeline entry. It is immutable once created.
 */
export class Card {
    /**
     * uuid v7 — identity and coarse time order
     */
    "id": string;

    /**
     * RFC3339Nano — human-readable timestamp
     */
    "created": time$0.Time;

    /**
     * markdown, opaque; the "what". No title.
     */
    "body": string;

    /**
     * 6 controlled axes (taxonomy.md)
     */
    "tags": Tags;
    "ref"?: Ref | null;

    /**
     * Derived fields — NOT stored on disk; filled by the service on read.
     * ids that ref this card with kind=link
     */
    "backlinks"?: string[];

    /**
     * ids that ref this card with kind=parent
     */
    "children"?: string[];

    /** Creates a new Card instance. */
    constructor($$source: Partial<Card> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = (new Tags());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Card instance from a string or object.
     */
    static createFrom($$source: any = {}): Card {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField4_0($$parsedSource["ref"]);
        }
        if ("backlinks" in $$parsedSource) {
            $$parsedSource["backlinks"] = $$createField5_0($$parsedSource["backlinks"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField6_0($$parsedSource["children"]);
        }
        return new Card($$parsedSource as Partial<Card>);
    }
}

/**
 * CardFilter narrows ListCards. Empty fields are ignored. Area matches if the card
 * has the given area among its values.
 */
export class CardFilter {
    "type": string;
    "status": string;
    "priority": string;
    "horizon": string;
    "effort": string;
    "area": string;

    /** Creates a new CardFilter instance. */
    constructor($$source: Partial<CardFilter> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("horizon" in $$source)) {
            this["horizon"] = "";
        }
        if (!("effort" in $$source)) {
            this["effort"] = "";
        }
        if (!("area" in $$source)) {
            this["area"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CardFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): CardFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CardFilter($$parsedSource as Partial<CardFilter>);
    }
}

/**
 * DirEntry is one item in the cmdline file finder.
 */
export class DirEntry {
    "name": string;
    "isDir": boolean;

    /** Creates a new DirEntry instance. */
    constructor($$source: Partial<DirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry($$parsedSource as Partial<DirEntry>);
    }
}

/**
 * NewCard is the structured input for CreateCard. Tags are raw, order-preserving
 * tokens (the backend resolves them, PLAN.md §1·B). RefID/RefKind are flat so the
 * generated bindings stay simple.
 */
export class NewCard {
    "tags": string[];
    "body": string;
    "refId": string;

    /**
     * "" | "link" | "parent"
     */
    "refKind": string;

    /** Creates a new NewCard instance. */
    constructor($$source: Partial<NewCard> = {}) {
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("refId" in $$source)) {
            this["refId"] = "";
        }
        if (!("refKind" in $$source)) {
            this["refKind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewCard instance from a string or object.
     */
    static createFrom($$source: any = {}): NewCard {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField0_0($$parsedSource["tags"]);
        }
        return new NewCard($$parsedSource as Partial<NewCard>);
    }
}

/**
 * NewNote is the structured input for CreateNoteFull — the result of the
 * frontend parsing a `:*` statement. Status/priority arrive already normalized
 * to their canonical forms; the backend re-validates as a safety net and fills
 * the git branch itself.
 */
export class NewNote {
    "title": string;
    "body": string;
    "tags": string[];
    "status": string;
    "priority": string;
    "people": string[];
    "anchors": Anchor[];

    /** Creates a new NewNote instance. */
    constructor($$source: Partial<NewNote> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("anchors" in $$source)) {
            this["anchors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewNote instance from a string or object.
     */
    static createFrom($$source: any = {}): NewNote {
        const $$createField2_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField5_0($$parsedSource["people"]);
        }
        if ("anchors" in $$parsedSource) {
            $$parsedSource["anchors"] = $$createField6_0($$parsedSource["anchors"]);
        }
        return new NewNote($$parsedSource as Partial<NewNote>);
    }
}

/**
 * Note is the in-memory representation of a single note. The durable source of
 * truth is always the Markdown file on disk (<id>.md); this struct is what we
 * read out of it and hand to the frontend.
 * 
 * Piece 1 keeps the frontmatter deliberately small (id/title/created/updated/
 * tags/status). Fields owned by later pieces (priority, coworkers, branch,
 * intent, links, merge_parents) are intentionally NOT written yet so we don't
 * commit to a format before its semantics exist.
 */
export class Note {
    "id": string;
    "title": string;
    "created": time$0.Time;
    "updated": time$0.Time;
    "tags": string[];
    "status": string;

    /**
     * Priority is one of low/medium/high (or empty = unset). Branch is the git
     * branch the note was captured on (auto-filled). People are the @mentioned
     * coworkers. All omitted from disk when empty so plain notes stay clean.
     */
    "priority": string;
    "branch": string;
    "people": string[];

    /**
     * Anchors tie this note to concrete spots in the project's code (Level A:
     * file + line range + the git commit at anchor time). Omitted from disk when
     * empty so plain notes stay clean.
     */
    "anchors": Anchor[];

    /**
     * Body is the Markdown content after the frontmatter block. Not part of the
     * YAML; populated/serialized separately.
     */
    "body": string;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            this["updated"] = null;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("anchors" in $$source)) {
            this["anchors"] = [];
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField4_0 = $$createType3;
        const $$createField8_0 = $$createType3;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField8_0($$parsedSource["people"]);
        }
        if ("anchors" in $$parsedSource) {
            $$parsedSource["anchors"] = $$createField9_0($$parsedSource["anchors"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

/**
 * Ref is a single outgoing reference to another card. kind=parent expresses
 * nesting (this card is filed under the target); kind=link is a neutral link.
 */
export class Ref {
    "id": string;

    /**
     * "link" (default) | "parent"
     */
    "kind": string;

    /** Creates a new Ref instance. */
    constructor($$source: Partial<Ref> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ref instance from a string or object.
     */
    static createFrom($$source: any = {}): Ref {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ref($$parsedSource as Partial<Ref>);
    }
}

/**
 * Tags is the per-axis tag map. type/status are always materialized (defaults
 * note/todo); the rest only when set. horizon's logical default `now` is applied
 * on read by the service, not stored, so an absent horizon stays absent on disk.
 */
export class Tags {
    /**
     * required, default note
     */
    "type": string;

    /**
     * required, default todo
     */
    "status": string;

    /**
     * 0-1
     */
    "priority"?: string;

    /**
     * 0-1, logical default now
     */
    "horizon"?: string;

    /**
     * 0-N, free text allowed
     */
    "area"?: string[];

    /**
     * 0-1
     */
    "effort"?: string;

    /** Creates a new Tags instance. */
    constructor($$source: Partial<Tags> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tags instance from a string or object.
     */
    static createFrom($$source: any = {}): Tags {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("area" in $$parsedSource) {
            $$parsedSource["area"] = $$createField4_0($$parsedSource["area"]);
        }
        return new Tags($$parsedSource as Partial<Tags>);
    }
}

// Private type creation functions
const $$createType0 = Tags.createFrom;
const $$createType1 = Ref.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = Anchor.createFrom;
const $$createType5 = $Create.Array($$createType4);
