// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Anchor is a "Level A" code reference: a pin to a file and line range, plus the
 * git commit the project was on when the anchor was made. No content fingerprint
 * yet — if the code moves we can warn (later), but we don't auto-relocate.
 */
export class Anchor {
    "file": string;

    /**
     * "166-195" or a single "42"
     */
    "lines": string;

    /**
     * short git SHA at anchor time
     */
    "commit": string;

    /** Creates a new Anchor instance. */
    constructor($$source: Partial<Anchor> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Anchor instance from a string or object.
     */
    static createFrom($$source: any = {}): Anchor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Anchor($$parsedSource as Partial<Anchor>);
    }
}

/**
 * NewNote is the structured input for CreateNoteFull — the result of the
 * frontend parsing a `:*` statement. Status/priority arrive already normalized
 * to their canonical forms; the backend re-validates as a safety net and fills
 * the git branch itself.
 */
export class NewNote {
    "title": string;
    "body": string;
    "tags": string[];
    "status": string;
    "priority": string;
    "people": string[];
    "anchors": Anchor[];

    /** Creates a new NewNote instance. */
    constructor($$source: Partial<NewNote> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("anchors" in $$source)) {
            this["anchors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewNote instance from a string or object.
     */
    static createFrom($$source: any = {}): NewNote {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField5_0($$parsedSource["people"]);
        }
        if ("anchors" in $$parsedSource) {
            $$parsedSource["anchors"] = $$createField6_0($$parsedSource["anchors"]);
        }
        return new NewNote($$parsedSource as Partial<NewNote>);
    }
}

/**
 * Note is the in-memory representation of a single note. The durable source of
 * truth is always the Markdown file on disk (<id>.md); this struct is what we
 * read out of it and hand to the frontend.
 * 
 * Piece 1 keeps the frontmatter deliberately small (id/title/created/updated/
 * tags/status). Fields owned by later pieces (priority, coworkers, branch,
 * intent, links, merge_parents) are intentionally NOT written yet so we don't
 * commit to a format before its semantics exist.
 */
export class Note {
    "id": string;
    "title": string;
    "created": time$0.Time;
    "updated": time$0.Time;
    "tags": string[];
    "status": string;

    /**
     * Priority is one of low/medium/high (or empty = unset). Branch is the git
     * branch the note was captured on (auto-filled). People are the @mentioned
     * coworkers. All omitted from disk when empty so plain notes stay clean.
     */
    "priority": string;
    "branch": string;
    "people": string[];

    /**
     * Anchors tie this note to concrete spots in the project's code (Level A:
     * file + line range + the git commit at anchor time). Omitted from disk when
     * empty so plain notes stay clean.
     */
    "anchors": Anchor[];

    /**
     * Body is the Markdown content after the frontmatter block. Not part of the
     * YAML; populated/serialized separately.
     */
    "body": string;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            this["updated"] = null;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("anchors" in $$source)) {
            this["anchors"] = [];
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField4_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField8_0($$parsedSource["people"]);
        }
        if ("anchors" in $$parsedSource) {
            $$parsedSource["anchors"] = $$createField9_0($$parsedSource["anchors"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Anchor.createFrom;
const $$createType2 = $Create.Array($$createType1);
