// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Anchor is a "Level A" code reference: a pin to a file and line range, plus the
 * git commit the project was on when the anchor was made. No content fingerprint
 * yet — if the code moves we can warn (later), but we don't auto-relocate.
 */
export class Anchor {
    "file": string;

    /**
     * "166-195" or a single "42"
     */
    "lines": string;

    /**
     * short git SHA at anchor time
     */
    "commit": string;

    /** Creates a new Anchor instance. */
    constructor($$source: Partial<Anchor> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Anchor instance from a string or object.
     */
    static createFrom($$source: any = {}): Anchor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Anchor($$parsedSource as Partial<Anchor>);
    }
}

/**
 * Block is one element of a rendered document: either a run of plain prose
 * ("text") or a card ("card"). The frontend walks Blocks in order to render the
 * interleaved document. Blocks is a projection of Note.Body — disposable, never
 * persisted on its own.
 */
export class Block {
    /**
     * "text" | "card"
     */
    "kind": string;

    /**
     * set when Kind == "text"
     */
    "text"?: string;

    /**
     * set when Kind == "card"
     */
    "card"?: Card | null;

    /** Creates a new Block instance. */
    constructor($$source: Partial<Block> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Block instance from a string or object.
     */
    static createFrom($$source: any = {}): Block {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("card" in $$parsedSource) {
            $$parsedSource["card"] = $$createField2_0($$parsedSource["card"]);
        }
        return new Block($$parsedSource as Partial<Block>);
    }
}

/**
 * Card is one status card embedded in a note document. Content, metadata and
 * ordering all come from the inline fence in the note body — there is no second
 * copy anywhere, so a card can never drift out of sync with itself.
 */
export class Card {
    "id": string;
    "created": time$0.Time;
    "updated": time$0.Time;
    "author"?: string;

    /**
     * Links are the IDs of other cards this card references. Rendering these as a
     * graph is a later piece; here we only persist the edges.
     */
    "links"?: string[];

    /**
     * Body is the card's content (status text and/or code), preserved byte-for-byte
     * between the fence lines except for outer blank lines (the fence delimiters
     * own those). It may span multiple lines but must not contain a line equal to
     * the bare close fence (enforced on write).
     */
    "body": string;

    /** Creates a new Card instance. */
    constructor($$source: Partial<Card> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            this["updated"] = null;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Card instance from a string or object.
     */
    static createFrom($$source: any = {}): Card {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField4_0($$parsedSource["links"]);
        }
        return new Card($$parsedSource as Partial<Card>);
    }
}

/**
 * DirEntry is one item in the cmdline file finder.
 */
export class DirEntry {
    "name": string;
    "isDir": boolean;

    /** Creates a new DirEntry instance. */
    constructor($$source: Partial<DirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry($$parsedSource as Partial<DirEntry>);
    }
}

/**
 * Document is the note plus its parsed, ordered blocks (prose + cards). Blocks
 * is a disposable projection of Note.Body; the .md file remains source of truth.
 */
export class Document {
    "note": Note;
    "blocks": Block[];

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("note" in $$source)) {
            this["note"] = (new Note());
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("note" in $$parsedSource) {
            $$parsedSource["note"] = $$createField0_0($$parsedSource["note"]);
        }
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField1_0($$parsedSource["blocks"]);
        }
        return new Document($$parsedSource as Partial<Document>);
    }
}

/**
 * JournalEvent is one immutable line in the timeline log.
 */
export class JournalEvent {
    "ts": time$0.Time;
    "type": string;
    "noteID": string;
    "cardID": string;

    /**
     * To is the target card for a link event; empty otherwise.
     */
    "to"?: string;

    /**
     * Author is who triggered the event, for attribution in the timeline.
     */
    "author"?: string;

    /** Creates a new JournalEvent instance. */
    constructor($$source: Partial<JournalEvent> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = null;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("noteID" in $$source)) {
            this["noteID"] = "";
        }
        if (!("cardID" in $$source)) {
            this["cardID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): JournalEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalEvent($$parsedSource as Partial<JournalEvent>);
    }
}

/**
 * NewNote is the structured input for CreateNoteFull — the result of the
 * frontend parsing a `:*` statement. Status/priority arrive already normalized
 * to their canonical forms; the backend re-validates as a safety net and fills
 * the git branch itself.
 */
export class NewNote {
    "title": string;
    "body": string;
    "tags": string[];
    "status": string;
    "priority": string;
    "people": string[];
    "anchors": Anchor[];

    /** Creates a new NewNote instance. */
    constructor($$source: Partial<NewNote> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("anchors" in $$source)) {
            this["anchors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewNote instance from a string or object.
     */
    static createFrom($$source: any = {}): NewNote {
        const $$createField2_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField5_0($$parsedSource["people"]);
        }
        if ("anchors" in $$parsedSource) {
            $$parsedSource["anchors"] = $$createField6_0($$parsedSource["anchors"]);
        }
        return new NewNote($$parsedSource as Partial<NewNote>);
    }
}

/**
 * Note is the in-memory representation of a single note. The durable source of
 * truth is always the Markdown file on disk (<id>.md); this struct is what we
 * read out of it and hand to the frontend.
 * 
 * Piece 1 keeps the frontmatter deliberately small (id/title/created/updated/
 * tags/status). Fields owned by later pieces (priority, coworkers, branch,
 * intent, links, merge_parents) are intentionally NOT written yet so we don't
 * commit to a format before its semantics exist.
 */
export class Note {
    "id": string;
    "title": string;
    "created": time$0.Time;
    "updated": time$0.Time;
    "tags": string[];
    "status": string;

    /**
     * Priority is one of low/medium/high (or empty = unset). Branch is the git
     * branch the note was captured on (auto-filled). People are the @mentioned
     * coworkers. All omitted from disk when empty so plain notes stay clean.
     */
    "priority": string;
    "branch": string;
    "people": string[];

    /**
     * Anchors tie this note to concrete spots in the project's code (Level A:
     * file + line range + the git commit at anchor time). Omitted from disk when
     * empty so plain notes stay clean.
     */
    "anchors": Anchor[];

    /**
     * Body is the Markdown content after the frontmatter block. Not part of the
     * YAML; populated/serialized separately.
     */
    "body": string;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            this["updated"] = null;
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("anchors" in $$source)) {
            this["anchors"] = [];
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField4_0 = $$createType2;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField8_0($$parsedSource["people"]);
        }
        if ("anchors" in $$parsedSource) {
            $$parsedSource["anchors"] = $$createField9_0($$parsedSource["anchors"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

// Private type creation functions
const $$createType0 = Card.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Note.createFrom;
const $$createType4 = Block.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Anchor.createFrom;
const $$createType7 = $Create.Array($$createType6);
