// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService is the Wails-bound backend for Piece 1: per-project note storage.
 * Notes are plain Markdown files in <project>/.noteit/notes/<id>.md. These files
 * are the durable source of truth; nothing else here is a cache yet.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAnchor attaches a code reference (file + line range) to an existing note and
 * rewrites it to disk. This is the "Level A" pin: we also stamp the project's
 * current git commit so the anchor records the exact state it pointed at. The
 * note id is validated and the file rewrite is atomic.
 */
export function AddAnchor(noteID: string, file: string, lines: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3784827449, noteID, file, lines).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateNote writes a new note to disk and returns it. title's first line is the
 * title; the rest of `title` plus `body` is irrelevant here — the frontend sends
 * a clean title + body. The note id is a server-generated UUIDv7; the frontend
 * never controls the filename.
 */
export function CreateNote(title: string, body: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3901296041, title, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateNoteFull writes a note assembled from a parsed `:*` statement: title,
 * body, tags, status, priority, people and code anchors in one shot. The git
 * branch is auto-filled from the project. Unknown status/priority values are
 * rejected rather than silently stored.
 */
export function CreateNoteFull($in: $models.NewNote): $CancellablePromise<$models.Note> {
    return $Call.ByID(1881929232, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetNote returns a single note by id, including its body.
 */
export function GetNote(id: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(1276837971, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListDir powers the per-directory file finder (option A: instant, no index).
 * `input` is the path the user is typing in the cmdline. We resolve the path
 * notation for its DIRECTORY part and list that one directory, filtering by the
 * trailing partial segment. Notation:
 * 
 * 	~ , ~/x   → user home
 * 	./x , /x  → project root (a lone `/` means root, NOT the filesystem root)
 * 	x         → project root + /x
 * 
 * Returns at most 60 entries, directories first then prefix-matches. Never errors
 * on a missing/unreadable directory (returns empty) so the live finder degrades
 * quietly while you type a path that doesn't exist yet.
 */
export function ListDir(input: string): $CancellablePromise<$models.DirEntry[]> {
    return $Call.ByID(4251476956, input).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListNotes reads and parses every note file, newest-first by Created. Malformed
 * files are skipped with a logged warning rather than failing the whole list.
 */
export function ListNotes(): $CancellablePromise<$models.Note[]> {
    return $Call.ByID(27288930).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ProjectRoot reports the resolved project root (for the UI to display), or the
 * resolution error message.
 */
export function ProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(1402940126);
}

/**
 * SaveBody overwrites a note's entire Markdown body with `body` and rewrites it
 * to disk, bumping Updated. This is the Obsidian-style raw-text save path: the
 * editor owns the whole document as plain text, so it simply replaces the
 * "present" body. The note's frontmatter (title, tags, status, anchors, …) is
 * preserved by re-rendering the parsed note with only Body/Updated changed. The
 * id is validated and the write is atomic.
 */
export function SaveBody(noteID: string, body: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3106496432, noteID, body).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $models.DirEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
