// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService is the Wails-bound backend for Piece 1: per-project note storage.
 * Notes are plain Markdown files in <project>/.noteit/notes/<id>.md. These files
 * are the durable source of truth; nothing else here is a cache yet.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAnchor attaches a code reference (file + line range) to an existing note and
 * rewrites it to disk. This is the "Level A" pin: we also stamp the project's
 * current git commit so the anchor records the exact state it pointed at. The
 * note id is validated and the file rewrite is atomic.
 */
export function AddAnchor(noteID: string, file: string, lines: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3784827449, noteID, file, lines).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddCard appends a new status card to the end of a note document and records a
 * card.created event. The card id is a server-generated UUIDv7; created/updated
 * are stamped now (UTC). Returns the updated Document.
 */
export function AddCard(noteID: string, body: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(1585089558, noteID, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateNote writes a new note to disk and returns it. title's first line is the
 * title; the rest of `title` plus `body` is irrelevant here — the frontend sends
 * a clean title + body. The note id is a server-generated UUIDv7; the frontend
 * never controls the filename.
 */
export function CreateNote(title: string, body: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3901296041, title, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateNoteFull writes a note assembled from a parsed `:*` statement: title,
 * body, tags, status, priority, people and code anchors in one shot. The git
 * branch is auto-filled from the project. Unknown status/priority values are
 * rejected rather than silently stored.
 */
export function CreateNoteFull($in: $models.NewNote): $CancellablePromise<$models.Note> {
    return $Call.ByID(1881929232, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteCard removes a card from the document and records a card.deleted event.
 * The journal keeps the full history, so a deleted card still exists in the
 * timeline even though it's gone from the present document.
 */
export function DeleteCard(noteID: string, cardID: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(705493124, noteID, cardID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDocument loads a note and parses its body into ordered blocks for rendering.
 */
export function GetDocument(id: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(2793803718, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetNote returns a single note by id, including its body.
 */
export function GetNote(id: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(1276837971, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LinkCards records that card `fromID` references card `toID`, persisting the
 * edge on the source card and recording a card.linked event. Both cards must
 * exist in the same note. Linking is idempotent (a duplicate edge is a no-op on
 * the document but still skipped, not re-journaled).
 */
export function LinkCards(noteID: string, fromID: string, toID: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(591812820, noteID, fromID, toID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDir powers the per-directory file finder (option A: instant, no index).
 * `input` is the path the user is typing in the cmdline. We resolve the path
 * notation for its DIRECTORY part and list that one directory, filtering by the
 * trailing partial segment. Notation:
 * 
 * 	~ , ~/x   → user home
 * 	./x , /x  → project root (a lone `/` means root, NOT the filesystem root)
 * 	x         → project root + /x
 * 
 * Returns at most 60 entries, directories first then prefix-matches. Never errors
 * on a missing/unreadable directory (returns empty) so the live finder degrades
 * quietly while you type a path that doesn't exist yet.
 */
export function ListDir(input: string): $CancellablePromise<$models.DirEntry[]> {
    return $Call.ByID(4251476956, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListNotes reads and parses every note file, newest-first by Created. Malformed
 * files are skipped with a logged warning rather than failing the whole list.
 */
export function ListNotes(): $CancellablePromise<$models.Note[]> {
    return $Call.ByID(27288930).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ProjectRoot reports the resolved project root (for the UI to display), or the
 * resolution error message.
 */
export function ProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(1402940126);
}

/**
 * SaveBody overwrites a note's entire Markdown body with `body` and rewrites it
 * to disk, bumping Updated. This is the Obsidian-style raw-text save path: the
 * editor owns the whole document (prose AND inline card fences) as plain text,
 * so there is no block diffing and no journaling here — it simply replaces the
 * "present" body. The note's frontmatter (title, tags, status, anchors, …) is
 * preserved by re-rendering the parsed note with only Body/Updated changed. The
 * id is validated and the write is atomic.
 */
export function SaveBody(noteID: string, body: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3106496432, noteID, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveDocument persists an edited block list as the note's new body WITHOUT
 * touching the timeline. This is the prose-save path: the Outline-style free-text
 * editor hands back the whole ordered block list after the user edits prose, and
 * we rewrite the .md file to match. Editing prose is not a card lifecycle event,
 * so — unlike AddCard/UpdateCard/DeleteCard/LinkCards — SaveDocument is
 * intentionally history-free and appends NO journal event. Card create/update/
 * delete/link still go exclusively through the journaled methods above; this one
 * only moves the "present" forward, never the history.
 * 
 * Card rendering reuses saveBlocksLocked → renderBlocks → renderCard, which
 * already guards card BODIES against a bare close fence. Prose blocks bypass that
 * guard (renderBlocks emits text verbatim), so a bare `:::` typed into prose would
 * otherwise persist and be re-parsed as a stray close fence, corrupting the
 * document on the next read. We therefore reject any prose block containing a lone
 * `:::` here and surface it to the caller rather than silently corrupting the file.
 * 
 * We return the Document RE-PARSED from the saved canonical body rather than
 * echoing the input blocks: renderBlocks normalizes spacing and merges/drops
 * blocks (e.g. two adjacent prose blocks collapse into one), so re-parsing
 * guarantees the caller sees exactly what landed on disk — the canonical form a
 * subsequent GetDocument would return — with no drift between the in-memory reply
 * and the persisted file.
 */
export function SaveDocument(noteID: string, blocks: $models.Block[]): $CancellablePromise<$models.Document> {
    return $Call.ByID(1504716789, noteID, blocks).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Timeline returns the full chronological journal for the project. The frontend
 * groups this into the precise "what happened when" view and, later, the graph.
 */
export function Timeline(): $CancellablePromise<$models.JournalEvent[]> {
    return $Call.ByID(1751149986).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateCard replaces the body of an existing card and records a card.updated
 * event. Created stays; Updated is bumped to now.
 */
export function UpdateCard(noteID: string, cardID: string, body: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(1988876318, noteID, cardID, body).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Note.createFrom;
const $$createType1 = $models.Document.createFrom;
const $$createType2 = $models.DirEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.JournalEvent.createFrom;
const $$createType6 = $Create.Array($$createType5);
